"""[chore] Added columns for tracking logs sent to S3

Revision ID: 9d30a4ef0252
Revises: 8bda200d00bc
Create Date: 2026-01-02 22:26:38.675914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d30a4ef0252'
down_revision: Union[str, Sequence[str], None] = '8bda200d00bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
