"""[chore] Added idempotency key

Revision ID: d8eaca13860e
Revises: 0bac1b62d49e
Create Date: 2026-01-10 00:48:56.543719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8eaca13860e'
down_revision: Union[str, Sequence[str], None] = '0bac1b62d49e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_tasks_idempotency_key'), 'tasks', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_idempotency_key'), table_name='tasks')
    op.drop_column('tasks', 'idempotency_key')
    # ### end Alembic commands ###
