"""[chore] Added in_dlq column for tracking tasks in dead-letter-queue

Revision ID: dc5ac3fe8ec3
Revises: 759d99e39fb5
Create Date: 2026-01-08 14:03:48.658091

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "dc5ac3fe8ec3"
down_revision: Union[str, Sequence[str], None] = "759d99e39fb5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
